### ISSUE TITLE
inactivity 🤔

### ISSUE THREAD

**Issue by hadisfr** [LaTeXing/LaTeX-cwl#10]
It seems there hasn't been any activity here for two or three years. Due to importance of such repo for some of latex users (e.g. users of text studio and users of sublime text with LaTeXing or LaTeXTools), maybe I can do some maintaining or add some files or etc. here, if you want.
@csch0

**Comment by csch0** [comment]
Agree, I started this repository but not many decided to contribute. I will check and merge it in the following week.

**Comment by hadisfr** [comment]
Thank you!
